# Generated by Django 5.1.4 on 2026-01-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_fix_corrupted_passwords"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="loginattempt",
            name="accounts_lo_email_f9be85_idx",
        ),
        migrations.RemoveIndex(
            model_name="loginattempt",
            name="accounts_lo_ip_addr_4f26f9_idx",
        ),
        migrations.RemoveField(
            model_name="loginattempt",
            name="user_agent",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="email",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="success",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
