# Generated by Django 5.1.4 on 2026-01-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_alter_notification_options_alter_userprofile_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="loginattempt",
            name="accounts_lo_email_f9be85_idx",
        ),
        migrations.RemoveIndex(
            model_name="loginattempt",
            name="accounts_lo_ip_addr_4f26f9_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="accounts_no_user_id_a4ff2e_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="accounts_no_user_id_501ff2_idx",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="verification_token_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("FILE_UPLOAD", "File Uploaded"),
                    ("FILE_SHARE", "File Shared"),
                    ("FILE_DOWNLOAD", "File Downloaded"),
                    ("SHARE_ACCESSED", "Shared Link Accessed"),
                    ("FILE_DELETED", "File Deleted"),
                    ("FILE_RESTORED", "File Restored"),
                    ("STORAGE_WARNING", "Storage Warning"),
                    ("SYSTEM", "System Notification"),
                    ("EMAIL_VERIFIED", "Email Verified"),
                ],
                max_length=20,
            ),
        ),
    ]
