# Generated by Django 5.1.4 on 2026-01-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="cloudinary_resource_type",
            field=models.CharField(
                blank=True, default="auto", max_length=20, null=True
            ),
        ),
    ]
